#!/usr/bin/env bash
# Anthropic Bridge installer — venv, .env, daemon (systemd/launchd), smoke test.
# Re-runnable: preserves existing .env values.
set -euo pipefail

BOLD=$'\033[1m'; RESET=$'\033[0m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RED=$'\033[31m'; BLUE=$'\033[34m'
info()    { echo "${BLUE}ℹ${RESET}  $*"; }
success() { echo "${GREEN}✅${RESET} $*"; }
warn()    { echo "${YELLOW}⚠${RESET}  $*"; }
error()   { echo "${RED}❌${RESET} $*" >&2; }

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_DIR"
DEFAULT_PORT=64173

echo ""; echo "${BOLD}Anthropic Bridge — installer${RESET}"; echo "────────────────────────────────────────────────"; echo ""

# ── Python ────────────────────────────────────────────────────
PY="$(command -v python3 || true)"
[[ -n "$PY" ]] || { error "python3 not found"; exit 1; }
PYV="$("$PY" -c 'import sys;print("%d.%d"%sys.version_info[:2])')"
"$PY" -c 'import sys; sys.exit(0 if sys.version_info>=(3,10) else 1)' || { error "Python 3.10+ required (found $PYV)"; exit 1; }
[[ -d .venv ]] || "$PY" -m venv .venv
.venv/bin/pip install -q --upgrade pip >/dev/null
.venv/bin/pip install -q -r requirements.txt
success "venv ready (Python $PYV)"
PYTHON_BIN_DIR="$REPO_DIR/.venv/bin"

# ── Existing .env ─────────────────────────────────────────────
env_get() { [[ -f .env ]] && grep -E "^${1}=" .env | tail -1 | cut -d= -f2- || true; }
E_KEY="$(env_get ANTHROPIC_API_KEY)"; E_BACKEND="$(env_get BRIDGE_BACKEND)"; E_REGION="$(env_get AWS_REGION)"
E_API="$(env_get BRIDGE_API_KEY)"; E_ADMIN="$(env_get BRIDGE_ADMIN_KEY)"; E_HOST="$(env_get HOST)"; E_PORT="$(env_get PORT)"

# ── Upstream ──────────────────────────────────────────────────
echo ""; echo "${BOLD}Upstream credential${RESET}"; echo "────────────────────────────────────────────────"
echo "  [1] Anthropic API key (console.anthropic.com, pay-as-you-go)"
echo "  [2] AWS Bedrock (uses your AWS credentials/profile; installs boto3)"
echo ""
echo "  Note: Claude Pro/Max subscription OAuth is NOT supported — Anthropic's terms"
echo "  prohibit it in third-party tools (Feb 2026) and enforce it (Apr 2026)."
echo ""
read -rp "Backend [${E_BACKEND:-1}]: " BACKEND_CHOICE
BACKEND_CHOICE="${BACKEND_CHOICE:-${E_BACKEND:-1}}"
if [[ "$BACKEND_CHOICE" == "2" || "$BACKEND_CHOICE" == "bedrock" ]]; then
    BACKEND="bedrock"; ANTHROPIC_API_KEY=""
    read -rp "AWS region [${E_REGION:-us-east-1}]: " AWS_REGION; AWS_REGION="${AWS_REGION:-${E_REGION:-us-east-1}}"
    read -rp "AWS profile (empty = default chain): " AWS_PROFILE
    .venv/bin/pip install -q boto3 && success "boto3 installed"
else
    BACKEND="anthropic"; AWS_REGION=""; AWS_PROFILE=""
    read -rp "ANTHROPIC_API_KEY [${E_KEY:+(keep existing)}${E_KEY:-required}]: " ANTHROPIC_API_KEY
    ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-$E_KEY}"
    [[ -n "$ANTHROPIC_API_KEY" ]] || { error "ANTHROPIC_API_KEY is required"; exit 1; }
fi

# ── Server ────────────────────────────────────────────────────
echo ""; echo "${BOLD}Server${RESET}"; echo "────────────────────────────────────────────────"
read -rp "Listen host [${E_HOST:-127.0.0.1}] (0.0.0.0 to expose; then set keys!): " BIND_HOST; BIND_HOST="${BIND_HOST:-${E_HOST:-127.0.0.1}}"
read -rp "Listen port [${E_PORT:-$DEFAULT_PORT}]: " PORT; PORT="${PORT:-${E_PORT:-$DEFAULT_PORT}}"
GEN_API="$(python3 -c 'import secrets;print("sk-bridge-"+secrets.token_urlsafe(24))')"
read -rp "Client API key [${E_API:-generate: $GEN_API}] (type 'none' for open access): " API_KEY
API_KEY="${API_KEY:-${E_API:-$GEN_API}}"; [[ "$API_KEY" == "none" ]] && API_KEY=""
GEN_ADMIN="$(python3 -c 'import secrets;print("sk-admin-"+secrets.token_urlsafe(24))')"
read -rp "Admin key [${E_ADMIN:-generate: $GEN_ADMIN}] (type 'none' for open admin): " ADMIN_KEY
ADMIN_KEY="${ADMIN_KEY:-${E_ADMIN:-$GEN_ADMIN}}"; [[ "$ADMIN_KEY" == "none" ]] && ADMIN_KEY=""
[[ -z "$API_KEY" && "$BIND_HOST" != "127.0.0.1" ]] && warn "No client key on a non-loopback bind: anyone reaching the port can use your quota."

# ── Write .env ────────────────────────────────────────────────
cat > .env <<EOF2
# Anthropic Bridge configuration (generated by install.sh $(date -u +%F))
HOST=${BIND_HOST}
PORT=${PORT}
BRIDGE_DEBUG=0
BRIDGE_BACKEND=${BACKEND}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
AWS_REGION=${AWS_REGION}
AWS_PROFILE=${AWS_PROFILE}
BRIDGE_API_KEY=${API_KEY}
BRIDGE_ADMIN_KEY=${ADMIN_KEY}
# BRIDGE_CONTEXT_1M=0
# BRIDGE_QUOTA_TTL=30
# BRIDGE_ALLOW_PRIVATE_URLS=0
EOF2
chmod 600 .env
success "Configuration written to .env"

# ── Daemon ────────────────────────────────────────────────────
DAEMON_DIR="$REPO_DIR/daemon"; mkdir -p "$DAEMON_DIR"
sed -e "s|%USER%|$(id -un)|g" -e "s|%WORK_DIR%|${REPO_DIR}|g" -e "s|%PYTHON_BIN_DIR%|${PYTHON_BIN_DIR}|g" \
    -e "s|%HOST%|${BIND_HOST}|g" -e "s|%PORT%|${PORT}|g" anthropic-bridge.service > "$DAEMON_DIR/anthropic-bridge.service"
cat > "$DAEMON_DIR/com.lomelidev.anthropic-bridge.plist" <<EOF2
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.lomelidev.anthropic-bridge</string>
  <key>ProgramArguments</key><array>
    <string>${PYTHON_BIN_DIR}/python3</string><string>${REPO_DIR}/server.py</string>
    <string>--host</string><string>${BIND_HOST}</string><string>--port</string><string>${PORT}</string>
  </array>
  <key>WorkingDirectory</key><string>${REPO_DIR}</string>
  <key>RunAtLoad</key><true/><key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${REPO_DIR}/bridge.log</string>
  <key>StandardErrorPath</key><string>${REPO_DIR}/bridge.log</string>
</dict></plist>
EOF2
cat > "$DAEMON_DIR/run.sh" <<EOF2
#!/usr/bin/env bash
cd "${REPO_DIR}" && exec ${PYTHON_BIN_DIR}/python3 server.py --host ${BIND_HOST} --port ${PORT}
EOF2
chmod +x "$DAEMON_DIR/run.sh"

if command -v systemctl >/dev/null 2>&1 && [[ "$(uname -s)" == "Linux" ]]; then
    read -rp "Install systemd service? [Y/n]: " YN; YN="${YN:-Y}"
    if [[ "$YN" =~ ^[Yy]$ ]]; then
        sudo cp "$DAEMON_DIR/anthropic-bridge.service" /etc/systemd/system/anthropic-bridge.service
        sudo systemctl daemon-reload && sudo systemctl enable --now anthropic-bridge && success "systemd service installed & started"
    fi
elif [[ "$(uname -s)" == "Darwin" ]]; then
    read -rp "Install launchd agent? [Y/n]: " YN; YN="${YN:-Y}"
    if [[ "$YN" =~ ^[Yy]$ ]]; then
        mkdir -p "$HOME/Library/LaunchAgents"
        cp "$DAEMON_DIR/com.lomelidev.anthropic-bridge.plist" "$HOME/Library/LaunchAgents/"
        launchctl unload "$HOME/Library/LaunchAgents/com.lomelidev.anthropic-bridge.plist" 2>/dev/null || true
        launchctl load -w "$HOME/Library/LaunchAgents/com.lomelidev.anthropic-bridge.plist" && success "launchd agent installed & started"
    fi
else
    info "No systemd/launchd: start manually with $DAEMON_DIR/run.sh"
fi

# ── Smoke test ────────────────────────────────────────────────
BASE="http://127.0.0.1:${PORT}"; AUTH=(); [[ -n "$API_KEY" ]] && AUTH=(-H "Authorization: Bearer ${API_KEY}")
echo ""; info "Smoke test against $BASE ..."; sleep 2
for i in 1 2 3 4 5; do curl -s "$BASE/health" >/dev/null 2>&1 && break; sleep 1; done
st=$(curl -s "$BASE/health" | python3 -c 'import json,sys;print(json.load(sys.stdin).get("status"))' 2>/dev/null || echo "down")
[[ "$st" == "ok" ]] && success "/health OK" || warn "/health: $st (start the server and re-check)"
n=$(curl -s "${AUTH[@]}" "$BASE/v1/models" | python3 -c 'import json,sys;print(len(json.load(sys.stdin)["data"]))' 2>/dev/null || echo 0)
[[ "$n" -gt 0 ]] && success "/v1/models: $n models" || warn "/v1/models returned nothing"
resp=$(curl -s "${AUTH[@]}" -H 'Content-Type: application/json' "$BASE/v1/chat/completions" \
   -d '{"model":"claude-haiku-4-5","max_tokens":5,"messages":[{"role":"user","content":"reply with exactly: OK"}]}' \
   | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d["choices"][0]["message"]["content"] if "choices" in d else d)' 2>/dev/null || true)
[[ "$resp" == *OK* ]] && success "/v1/chat/completions OK" || warn "chat: $resp"
q=$(curl -s -o /dev/null -w "%{http_code}" "${AUTH[@]}" "$BASE/v1/quota"); [[ "$q" == "200" ]] && success "/v1/quota OK" || warn "/v1/quota $q"
d=$(curl -s -o /dev/null -w "%{http_code}" "$BASE/docs"); [[ "$d" == "200" ]] && success "/docs OK -> $BASE/docs" || warn "/docs $d"
echo ""; success "Done."
[[ -n "$API_KEY" ]]   && info "Client key: $API_KEY"
[[ -n "$ADMIN_KEY" ]] && info "Admin key:  $ADMIN_KEY"
info "Swagger UI: $BASE/docs"
